### ISSUE TITLE
【功能请求】打包好的一键包加入MCL以更新插件

### ISSUE THREAD

**Issue by KaRuichin** [MrXiaoM/Lapis#1]

**Comment by MrXiaoM** [comment]
不太懂你的需求。

**Comment by MrXiaoM** [comment]
如果你指的是将下载的版本导入mcl配置文件，这做不到。
你也看到 libraries 文件夹里有多少库了。

**Comment by KaRuichin** [comment]
> 如果你指的是将下载的版本导入mcl配置文件，这做不到。 你也看到 libraries 文件夹里有多少库了。

是的，我是这个意思。
感谢大佬的回复，我没有其他问题了。
