### ISSUE TITLE
位于命令管道位置 1 的 cmdlet Write-Output 请为以下参数提供值: InputObject[0]:

### ISSUE THREAD

**Issue by AratoEndo** [MrXiaoM/Lapis#2]
![屏幕截图 2023-07-06 170243](https://github.com/MrXiaoM/Lapis/assets/138769041/04e4e6cd-018a-4962-8c67-6b67bccb4e88)

**Comment by Immovable-Library** [comment]
删除第八个Write-Output即可

**Comment by MrXiaoM** [comment]
已修复，请下载刚刚提交的 powershell 脚本
