### ISSUE TITLE
win2016运行setup.bat出错：不是内部或外部命令，也不是可运行的程序 或批处理文件。

### ISSUE THREAD

**Issue by Pika-Lee** [MrXiaoM/Lapis#3]
在win2016服务器下部署lapris，双击运行setup.bat文件后出错，内容如下：
`'开发版本的版本号可以在以下链接中获取:' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'version' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'谙略?' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'ion' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'籼崾?BUILD' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'D' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'按任意键退出' 不是内部或外部命令，也不是可运行的程序
或批处理文件。`

![QQ截图20230707151053](https://github.com/MrXiaoM/Lapis/assets/23114990/d729523c-d6ff-4b96-82b5-bc39b58c2eca)

**Comment by MrXiaoM** [comment]
自己改文件编码再运行

**Comment by MrXiaoM** [comment]
我尝试过gbk和utf8，都无法满足所有人的需求

**Comment by MrXiaoM** [comment]
能用ps1就不用bat

**Comment by Pika-Lee** [comment]
> 自己改文件编码再运行

找到原因了，.bat编码是ANSI(GBK)，和CMD默认的chcp 936一致。问题出在换行符上，.bat用的是LF，改成CRLF后双击运行就OK了
![QQ截图20230707152419](https://github.com/MrXiaoM/Lapis/assets/23114990/1449a546-cde0-4adf-8c1a-869dd5183767)
![QQ截图20230707152614](https://github.com/MrXiaoM/Lapis/assets/23114990/cf4e07f9-b2c8-4db9-a2c6-17d5c1db56c5)
