### ISSUE TITLE
Could not open settings generic class cache for settings file 

### ISSUE THREAD

**Issue by Pika-Lee** [MrXiaoM/Lapis#4]
日志如下：

`

  在运行本程序之前, 请确保你已经安装 java.
  请在下方输入版本号并回车以下载开发版本.
  开发版本的版本号可以在以下链接中获取:
  https://repo.mirai.mamoe.net/snapshots/net/mamoe/mirai-core

输入版本号: 2.15.0-dev-105
注: 其中一个库下载耗时较长，请耐心等待

FAILURE: Build failed with an exception.

* What went wrong:
Could not open settings generic class cache for settings file 'E:\mirai17_8\1\Lapis-main\settings.gradle' (C:\Users\Administrator\.gradle\caches\7.5.1\scripts\f5aywg0zhth9sb62gucahm1jh).
> BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 64

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s

  若提示 BUILD SUCCESSFUL, 一键包已成功打包到 ./build/lapis 文件夹中.
  若提示 BUILD FAILED, 可能是版本号输入错误或者网络问题.
  按任意键退出`

![QQ截图20230707152954](https://github.com/MrXiaoM/Lapis/assets/23114990/01b479bd-10c0-478a-8218-ddd41ad88857)

请问应该如何解决这个问题？谢谢

**Comment by MrXiaoM** [comment]
不要使用 java 20，尽量使用小于等于17的java版本

**Comment by Pika-Lee** [comment]
> 不要使用 java 20，尽量使用小于等于17的java版本

感谢解答，回退到java 17后问题解决。
![QQ截图20230707165847](https://github.com/MrXiaoM/Lapis/assets/23114990/f632abb0-1f2c-45f7-ba69-266dd1d3c11c)
